-- Deploy all PostgreSQL schema objects for the Datasilk template.
-- This file is auto-generated by gulpfile.js in the Datasilk.SQL project.
-- Run this script against your PostgreSQL database after creating the database.

-- Tables
\i Tables/AppRoles.sql
\i Tables/AppUsers.sql
\i Tables/AppUserRoles.sql
\i Tables/AppUserTokens.sql

-- Sequences
\i Sequences/SequenceAppRoles.sql
\i Sequences/SequenceAppUserTokens.sql

-- Indexes
\i Indexes/IndexAppUsersEmail.sql

-- Functions
\i Functions/ResetSequences.sql

-- SeedData
\i SeedData/AppRoles.sql
