const gulp = require('gulp');
const fs = require('fs');
const path = require('path');

const deployFile = 'deploy.sql';

// Ordered list of schema subfolders. SeedData runs last so all schema objects exist first.
const schemaFolders = [
  'Tables',
  'Sequences',
  'Indexes',
  'Functions',
  'Views',
  'SeedData'
];

// Optional explicit per-folder file order. Missing files are ignored; unlisted files are sorted alphabetically.
const folderOrder = {};

function extractTableName(sql) {
  const match = sql.match(/CREATE\s+TABLE\s+(?:IF\s+NOT\s+EXISTS\s+)?(?:\w+\.)?["']?(\w+)["']?/i);
  return match ? match[1] : null;
}

function extractReferences(sql) {
  const refs = [];
  const regex = /REFERENCES\s+(?:\w+\.)?["']?(\w+)["']?\s*\(/gi;
  let match;
  while ((match = regex.exec(sql)) !== null) {
    refs.push(match[1]);
  }
  return refs;
}

function sortByDependencies(files, folder) {
  const fileContents = {};
  const tableToFile = {};
  const dependencies = {};

  for (const file of files) {
    const sql = fs.readFileSync(path.join(__dirname, folder, file), 'utf8');
    fileContents[file] = sql;
    const table = extractTableName(sql);
    if (table) {
      tableToFile[table] = file;
    }
    dependencies[file] = new Set();
  }

  for (const file of files) {
    const refs = extractReferences(fileContents[file]);
    for (const ref of refs) {
      if (tableToFile[ref] && tableToFile[ref] !== file) {
        dependencies[file].add(tableToFile[ref]);
      }
    }
  }

  const inDegree = {};
  for (const file of files) {
    inDegree[file] = dependencies[file].size;
  }

  const queue = files.filter(f => inDegree[f] === 0).sort();
  const result = [];
  while (queue.length > 0) {
    const current = queue.shift();
    result.push(current);
    for (const file of files) {
      if (dependencies[file].has(current)) {
        inDegree[file]--;
        if (inDegree[file] === 0) {
          queue.push(file);
          queue.sort();
        }
      }
    }
  }

  if (result.length !== files.length) {
    const remaining = files.filter(f => !result.includes(f)).sort();
    console.warn(`Circular dependency detected in ${folder}. Appending remaining files alphabetically: ${remaining.join(', ')}`);
    result.push(...remaining);
  }

  return result;
}

function getSqlFiles(folder) {
  const fullPath = path.join(__dirname, folder);
  if (!fs.existsSync(fullPath)) {
    return [];
  }
  const files = fs.readdirSync(fullPath)
    .filter(file => file.toLowerCase().endsWith('.sql'))
    .filter(file => file.toLowerCase() !== deployFile.toLowerCase());

  const order = folderOrder[folder];
  if (order) {
    const ordered = [];
    const remaining = new Set(files);
    for (const file of order) {
      if (remaining.has(file)) {
        ordered.push(file);
        remaining.delete(file);
      }
    }
    return ordered.concat([...remaining].sort());
  }

  if (folder === 'Tables') {
    return sortByDependencies(files, folder);
  }

  return files.sort();
}

function generateDeployContent() {
  const lines = [
    '-- Deploy all PostgreSQL schema objects for the Datasilk template.',
    '-- This file is auto-generated by gulpfile.js in the Datasilk.SQL project.',
    '-- Run this script against your PostgreSQL database after creating the database.',
    ''
  ];

  for (const folder of schemaFolders) {
    const files = getSqlFiles(folder);
    if (files.length === 0) {
      continue;
    }
    lines.push(`-- ${folder}`);
    for (const file of files) {
      lines.push(`\\i ${folder}/${file}`);
    }
    lines.push('');
  }

  return lines.join('\n');
}

function updateDeploy() {
  const content = generateDeployContent();
  fs.writeFileSync(path.join(__dirname, deployFile), content, 'utf8');
  console.log(`${deployFile} updated.`);
  return Promise.resolve();
}

function watchDeploy() {
  const watchers = [];
  for (const folder of schemaFolders) {
    const fullPath = path.join(__dirname, folder);
    if (fs.existsSync(fullPath)) {
      watchers.push(gulp.watch(`${folder}/*.sql`, { cwd: __dirname }, updateDeploy));
    }
  }
  if (watchers.length === 0) {
    console.log('No schema folders found to watch.');
  } else {
    console.log(`Watching ${schemaFolders.filter(f => fs.existsSync(path.join(__dirname, f))).join(', ')} for changes...`);
  }
  return Promise.resolve();
}

exports.default = updateDeploy;
exports['update-deploy'] = updateDeploy;
exports.watch = watchDeploy;
